import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';

const root = process.cwd();
const out = join(root, 'out');
const read = f => readFileSync(f, 'utf8');
const home = JSON.parse(read('content/generated/home.json'));
const pages = JSON.parse(read('content/generated/pages.json')).filter(p => p.enabled);
const draft = process.argv.includes('--draft');
const origin = 'https://kingdomrush6.github.io';
const errors = [];
const check = (ok, msg) => { if (!ok) errors.push(msg); };
const decode = t => t.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const plain = t => decode(t.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/g,'').replace(/<[^>]*>/g,' '));
const attrs = tag => Object.fromEntries([...tag.matchAll(/([\w-]+)="([^"]*)"/g)].map(m => [m[1], decode(m[2])]));
const tagMeta = (html,name) => [...html.matchAll(/<meta\b[^>]*>/g)].map(m => attrs(m[0])).find(a => a.name===name)?.content;
const canonical = html => [...html.matchAll(/<link\b[^>]*>/g)].map(m => attrs(m[0])).find(a => a.rel==='canonical')?.href;
const wordCount = t => plain(t).match(/[a-z0-9]+(?:['’-][a-z0-9]+)*/gi)?.length ?? 0;
const banned = /starter homepage|starter page|replace this copy|example inner-page shell|Fact Pack|Evidence ID|SEO audit|AI generated|Generated by|Yorich|Codex|Claude|ChatGPT|example\.github\.io|localhost|127\.0\.0\.1|\/kingdom-rush-6\/|href="\/wiki\//i;
const titles = new Set(), descriptions = new Set();
const all = [home,...pages];
const route = p => p.slug ? `/${p.slug}/` : '/';
const sitemap = read(join(out,'sitemap.xml'));
const robots = read(join(out,'robots.txt'));
check(sitemap.match(/<loc>/g)?.length===8,'Sitemap must contain exactly eight URLs');
check(robots.includes(`Sitemap: ${origin}/sitemap.xml`),'Wrong robots sitemap');
if (!draft) check(/Allow: \//.test(robots) && !/Disallow: \//.test(robots),'robots must allow crawling');
check(!existsSync(join(out,'wiki')),'wiki output must not exist');
const incoming = new Map(all.map(p => [route(p),0]));
for (const p of all) {
  const path = route(p), html = read(join(out,p.slug,'index.html'));
  const main = html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/)?.[1] ?? '';
  const title = decode(html.match(/<title>(.*?)<\/title>/)?.[1] ?? '');
  const desc = tagMeta(html,'description');
  check(title===p.title,`${path}: final title differs`);
  check(title.length<=60,`${path}: title exceeds 60 characters`);
  check(desc===p.description && desc.length<=160,`${path}: invalid description`);
  check(!titles.has(title),`${path}: duplicate title`); titles.add(title);
  check(!descriptions.has(desc),`${path}: duplicate description`); descriptions.add(desc);
  check((html.match(/<h1\b/g)??[]).length===1,`${path}: expected exactly one H1`);
  check(plain(html.match(/<h1[^>]*>(.*?)<\/h1>/)?.[1]??'')===p.hero.heading,`${path}: wrong H1`);
  check(canonical(html)===origin+path,`${path}: wrong canonical`);
  if (!draft) check(tagMeta(html,'robots')==='index, follow',`${path}: not index/follow`);
  check(sitemap.includes(`<loc>${origin+path}</loc>`),`${path}: missing sitemap entry`);
  check(!banned.test(html),`${path}: prohibited public residue`);
  const count = wordCount(main);
  check(count >= (p.slug ? 800 : 1200),`${path}: only ${count} main-content English words`);
  for (const s of p.sections) {
    check(html.includes(`id="${s.id}"`),`${path}: missing section anchor ${s.id}`);
    check(plain(main).includes(s.heading),`${path}: missing section ${s.heading}`);
    for (const sub of s.subsections??[]) check(plain(main).includes(sub.heading),`${path}: missing subsection`);
    for (const row of s.table?.rows??[]) for (const c of row) check(plain(main).includes(c),`${path}: table cell omitted`);
  }
  const header = html.match(/<header\b[^>]*>[\s\S]*?<\/header>/)?.[0]??'';
  const footer = html.match(/<footer\b[^>]*>[\s\S]*?<\/footer>/)?.[0]??'';
  for (const linked of pages) {
    check(header.includes(`href="${route(linked)}"`),`${path}: missing global nav ${linked.slug}`);
    check(footer.includes(`href="${route(linked)}"`),`${path}: missing footer ${linked.slug}`);
  }
  for (const link of main.matchAll(/href="(\/[^"#]*)(?:#[^"]*)?"/g)) if (link[1]!==path && incoming.has(link[1])) incoming.set(link[1],incoming.get(link[1])+1);
  const schemas = [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].flatMap(m => { try { const d=JSON.parse(m[1]);return Array.isArray(d)?d:[d]; } catch { errors.push(`${path}: malformed JSON-LD`);return []; } });
  const types = schemas.map(s => s['@type']);
  for (const type of p.slug?['WebPage','BreadcrumbList','FAQPage',...(p.slug==='release-date'?[]:['ItemList'])]:['WebSite','VideoGame','FAQPage']) check(types.includes(type),`${path}: missing ${type} schema`);
  check(!types.some(t => ['Offer','Review','AggregateRating','HowTo'].includes(t)),`${path}: unsupported schema`);
  const fs = schemas.find(s => s['@type']==='FAQPage');
  check(fs?.mainEntity.length===p.faq.length,`${path}: FAQ schema count mismatch`);
  for (const f of fs?.mainEntity??[]) check(plain(main).includes(f.name) && plain(main).includes(f.acceptedAnswer.text),`${path}: invisible FAQ schema`);
  if (p.slug) {
    const b = schemas.find(s => s['@type']==='BreadcrumbList')?.itemListElement;
    check(b?.length===2 && b[0].name==='Home' && b[1].name===p.navLabel && b[1].item===origin+path,`${path}: invalid breadcrumb schema`);
    check(/class="site-breadcrumb"/.test(main) && main.includes('Home'),`${path}: missing visible breadcrumb`);
  }
  console.log(`${path} ${count} words · title ${title.length} · description ${desc?.length}`);
}
for (const [path,n] of incoming) check(n>0,`${path}: orphan page`);
function walk(dir) {return readdirSync(dir).flatMap(n => { const p=join(dir,n);return statSync(p).isDirectory()?walk(p):[p];});}
for (const file of walk(out).filter(f => /\.(html|xml|txt|webmanifest|svg)$/.test(f))) {
  const html = read(file);
  check(!banned.test(html),`${file.replace(out,'')}: prohibited output`);
  if (!file.endsWith('.html')) continue;
  for (const m of html.matchAll(/<(?:a|img|link|script)\b[^>]*(?:href|src)="([^"]+)"/g)) {
    const u=decode(m[1]); if (/^(?:https?:|mailto:|data:)/.test(u)) continue;
    const [local,fragment] = u.split('#');
    const target = local ? (local.startsWith('/') ? join(out,local) : resolve(dirname(file),local)) : file;
    const dest = existsSync(target) && statSync(target).isDirectory()?join(target,'index.html'):target;
    check(existsSync(dest),`${file.replace(out,'')}: broken local link or asset ${u}`);
    if (fragment && existsSync(dest) && dest.endsWith('.html')) check(read(dest).includes(`id="${fragment}"`),`${file.replace(out,'')}: broken fragment ${u}`);
  }
}
for (const technical of ['llms.txt','llms-full.txt']) {
 const text=read(join(out,technical));check(text.includes(origin+'/')&&!text.includes('/wiki/'),`${technical}: invalid URLs`);
}
if (errors.length) { console.error(errors.join('\n'));process.exit(1); }
console.log(`Static SEO audit passed${draft?' (pre-launch draft)':''}: 8 launch pages, metadata, schema, navigation, assets and internal links.`);
