import { existsSync } from "node:fs";
import { join } from "node:path";
import { siteConfig } from "../config/site";
import { homePage } from "../content/home";
import { allPages, enabledCorePages, visibleCorePages } from "../content/registry";
import { pagePlainText } from "../lib/content";

const launch = ["heroes", "towers", "tier-list", "classic-mode", "map-stages", "release-date", "spells"];
const errors: string[] = [];
const check = (ok: unknown, message: string) => { if (!ok) errors.push(message); };
check(siteConfig.hosting.siteUrl === "https://kingdomrush6.github.io", "Incorrect production origin");
check(siteConfig.hosting.basePath === "", "Production basePath must be empty");
check(new Set(allPages.map(p => p.slug)).size === allPages.length, "Duplicate slugs");
check(enabledCorePages.length === launch.length, "Unexpected SEO page count");
for (const slug of launch) {
  check(enabledCorePages.some(p => p.slug === slug), `Missing launch page: ${slug}`);
  check(visibleCorePages.some(p => p.slug === slug), `Missing navigation entry: ${slug}`);
}
check(!allPages.some(p => p.enabled && p.slug === "wiki"), "Obsolete wiki route enabled");
const routes = new Set(["", ...allPages.filter(p => p.enabled).map(p => p.slug)]);
const banned = /starter homepage|starter page|replace this copy|example inner-page shell|fact pack|evidence id|SEO audit|AI generated|generated by|Yorich|Codex|Claude|ChatGPT|example\.github\.io|localhost|127\.0\.0\.1/i;
for (const page of [homePage, ...allPages.filter(p => p.enabled)]) {
  const id = page.slug || "home";
  check(page.title.trim(), `${id}: missing title`);
  check(page.description.trim(), `${id}: missing description`);
  check(page.hero.heading.trim(), `${id}: missing H1`);
  check(page.hero.lead.trim(), `${id}: missing hero answer`);
  check(/^\d{4}-\d{2}-\d{2}$/.test(page.lastReviewed), `${id}: missing review date`);
  check(page.sections.length, `${id}: missing sections`);
  check(!banned.test(pagePlainText(page)), `${id}: prohibited public copy`);
  check(new Set(page.sections.map(s => s.id)).size === page.sections.length, `${id}: duplicate section anchors`);
  if (page.pageType !== "legal") {
    check(page.factsStatus === "verified", `${id}: incomplete facts status`);
    check(page.faq?.length, `${id}: missing FAQ`);
    if (siteConfig.readyForLaunch) check(page.sections.some(s => s.table || s.links?.length), `${id}: missing required structured content`);
  }
  for (const s of page.sections) {
    for (const link of s.links ?? []) check(routes.has(link.slug), `${id}: broken internal route ${link.slug}`);
    for (const link of s.externalLinks ?? []) check(siteConfig.allowedExternalDomains.includes(new URL(link.url).hostname), `${id}: external domain not allowed`);
    for (const tab of [s.table, ...(s.subsections ?? []).map(sub => sub.table)].filter(Boolean)) {
      check(tab!.rows.every(r => r.length === tab!.columns.length), `${id}: invalid table width`);
    }
  }
  if ("relatedSlugs" in page) for (const slug of page.relatedSlugs ?? []) check(routes.has(slug), `${id}: invalid relatedSlug ${slug}`);
  for (const shot of page.screenshots ?? []) check(existsSync(join("public", shot.src)), `${id}: missing screenshot`);
}
for (const asset of Object.values(siteConfig.assets)) check(existsSync(join("public", asset)), `Missing asset: ${asset}`);
if (homePage.hero.primaryLink) check(routes.has(homePage.hero.primaryLink.slug), "Invalid home CTA");
check(homePage.sections.flatMap(s => s.links ?? []).filter(l => launch.includes(l.slug)).length >= 7, "Home must link all seven guides");
if (errors.length) { console.error(errors.join("\n")); process.exit(1); }
console.log(`Validation passed: home, ${enabledCorePages.length} SEO pages, routes, assets and configuration.`);
